#
# This is the main ansible playbook to deploy TripleA server software.
# See the README.md files for details on running and testing.
#

- hosts: all
  roles:
    - apt_update
    - admin_user
    - firewall
    - security

- hosts: postgresHosts
  roles:
    - postgres
    - lobby_database
    - flyway

- hosts: dropwizardHosts
  tags: lobby
  roles:
    - java
    - http_server
    - nginx
    - postfix

- hosts: letsEncrypt
  tags: lobby
  roles:
    - role: certbot
    # Re-run nginx role to fix configuration and do final restart.
    # Modifications to /etc/nginx/sites-enabled/default triggers a NGINX restart.
    # Certbot role adds a new line to /etc/nginx/sites-enabled/default
    # every time it runs and makes changes.
    - nginx

- hosts: botHosts
  tags: [bot, bots]
  roles:
    - java
    - bot

