- hosts: all
  roles:
    - system/apt_common_tools
    - system/hostname
    - system/firewall
    - system/security
    - system/journald
    - system/admin_user

- hosts: forums
  tags: forums
  roles:
    - nginx_forums_conf

- hosts: database
  tags: [database, postgres]
  roles:
    - database/postgres
    - {name: database/flyway, tags: flyway}

- hosts: lobbyServer
  tags: [lobby, lobby_server]
  roles:
    - java
    - lobby_server
    - nginx
    - postfix

- hosts: letsEncrypt
  tags: lobby
  roles:
    - certbot

- hosts: botHosts
  tags: [bot, bots]
  roles:
    - java
    - bot

