#
# This is the main ansible playbook to deploy TripleA server software.
# See the README.md files for details on running and testing.
#

- hosts: all
  gather_facts: no
  serial: 100%
  strategy: free
  tags: security
  roles:
    - role: apt_update
      tags:
        - bot
        - nginx
        - http_server
    - name: admin_user
      tags: [ admin_user ]
    - name: firewall
      tags: [ firewall ]
    - name: security
      tags: [ security ]

- hosts: postgresHosts
  gather_facts: no
  serial: 100%
  strategy: free
  roles:
    - role: postgres
      tags: [ postgres ]
    - role: lobby_database
      tags: [ lobby_database ]
    - role: flyway
      tags: [ flyway ]

- hosts: dropwizardHosts
  gather_facts: no
  serial: 100%
  strategy: free
  tags: lobby
  roles:
    - java
    - role: http_server
      tags: [ http_server ]
    - role: nginx
      tags: [ nginx ]
    - role: certbot
      tags: [ certbot ]

- hosts: botHosts
  gather_facts: no
  serial: 100%
  tags: bots
  roles:
    - java
    - role: bot
      tags: [ bot ]
