[versions]
# Libraries
apache-http-components = "4.5.14"
assertj-core = "3.27.6"
awaitility = "4.3.0"
caffeine = "3.2.3"
checkstyle = "8.45"
commons-io = "2.21.0"
commons-math = "3.6.1"
commons-text = "1.15.0"
dropwizard-websockets = "1.3.14"
equals-verifier = "4.3"
feign = "13.6"
gson = "2.13.2"
guava = "33.5.0-jre"
hamcrest-optional = "2.0.0"
hamcrest = "2.0.0.0"
jackson-datatype = "2.20.1"
jakarta-mail = "2.0.2"
java-websocket = "1.6.0"
jaxb-impl = "4.0.6"
jetbrains-annotations = "26.0.2-1"
jlayer = "1.0.1.4"
junit-jupiter = "6.0.1"
junit-platform-launcher = "6.0.1"
logback-classic = "1.5.23"
lombok = "1.18.42"
mockito = "5.21.0"
pmd = "7.0.0"
snake-yaml = "3.0.1"
sonatype-goodies-prefs = "2.3.9"
substance = "4.5.0"
wiremock-junit5 = "1.3.1"
wiremock = "3.0.1"
xchart = "3.8.8"
xmlunit = "2.11.0"

# Plugins
gradle-versions = "0.53.0"
spotless = "8.1.0"
shadow = "9.3.0"
install4j = "12.0.2"
download = "5.6.0"

[libraries]
apache-httpmime = { module = "org.apache.httpcomponents:httpmime", version.ref = "apache-http-components" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
dropwizard-websockets = { module = "com.liveperson:dropwizard-websockets", version.ref = "dropwizard-websockets" }
equals-verifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equals-verifier" }
feign-gson = { module = "io.github.openfeign:feign-gson", version.ref = "feign" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hamcrest-optional = { module = "com.github.npathai:hamcrest-optional", version.ref = "hamcrest-optional" }
hamcrest = { module = "org.hamcrest:java-hamcrest", version.ref = "hamcrest" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-datatype" }
jakarta-mail = { module = "com.sun.mail:jakarta.mail", version.ref = "jakarta-mail" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java-websocket" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb-impl" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jlayer = { module = "com.googlecode.soundlibs:jlayer", version.ref = "jlayer" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-subclass = { module = "org.mockito:mockito-subclass", version.ref = "mockito" }
radiance-substance = { module = "org.pushing-pixels:radiance-substance", version.ref = "substance" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version.ref = "snake-yaml" }
sonatype-goodies-prefs = { module = "org.sonatype.goodies:goodies-prefs", version.ref = "sonatype-goodies-prefs" }
wiremock = { module = "com.github.tomakehurst:wiremock", version.ref = "wiremock" }
wiremock-junit5 = { module = "ru.lanwen.wiremock:wiremock-junit5", version.ref = "wiremock-junit5" }
xchart = { module = "org.knowm.xchart:xchart", version.ref = "xchart" }
xmlunit-core = { module = "org.xmlunit:xmlunit-core", version.ref = "xmlunit" }
xmlunit-matchers = { module = "org.xmlunit:xmlunit-matchers", version.ref = "xmlunit" }

[plugins]
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
install4j = { id = "com.install4j.gradle", version.ref = "install4j" }
download = { id = "de.undercouch.download", version.ref = "download" }

[bundles]
junit = ["junit-jupiter-api", "junit-jupiter-params"]
mockito = ["mockito-core", "mockito-junit-jupiter", "mockito-subclass"]
xmlunit = ["xmlunit-core", "xmlunit-matchers"]
