bot_user: "bot"
bot_folder: "/home/{{ bot_user }}"

# The location where we will install the bot binaries
bot_install_home: "{{ bot_folder }}/{{ version }}"

# The location of the jar executable that we will run to launch the bot server.
bot_jar: "{{ bot_install_home }}/triplea-game-headless-{{ version }}.jar"

# A folder where the bot server will find maps.
bot_maps_folder: "{{ bot_folder }}/maps"

# The URI of the lobby that the bot would connect to.
bot_lobby_uri: "{{ lobby_uri }}"

bot_max_memory: "168m"

# Each bot number matches a bot instance that will be deployed and started.
# 7 bots is standard for the 2GB RAM, $10/month linodes that we typically use.
bot_numbers: ["01", "02", "03", "04", "05", "06", "07"]

# Bot prefix we expect to be overriden in inventory.
# We deploy bots to multiple server, to keep the host numbers unique, there is a prefix.
# The bot prefix should be unique across all bot hosts.
# EG: with bot_prefix = 1, and bot_number=01, the bot number in the bot name will be '101'.
bot_prefix: ""

# Using latest flag indicates we should use assets that are built locally. False indicates we
# will download assets for a target version.
using_latest: true

# Download URL for grabbing bot artifacts, not used if using_latest is false.
zip_download: "https://github.com/triplea-game/triplea/releases/download/{{ version }}/triplea-game-headless-{{ version }}.zip"

# Name of the bot server, this will typically be overriden in inventory. The final name of the bot host is
# concatenation of the "Bot" the "bot name", and the "bot number" with prefix.
bot_name: "Server"

# Arguments when running bot servers. Each of the key value pairs will be added as a '-p{key}={value}' argument
# passed to the JVM when running the bot.
bot_run_args:
  triplea.port: "${BOT_PORT}"
  triplea.name: "Bot{{ bot_prefix }}${BOT_NUMBER}_{{ bot_name }}"
  triplea.lobby.uri: "{{ bot_lobby_uri }}"
  triplea.map.folder: "{{ bot_maps_folder }}"
