githubApiToken: ${GITHUB_API_TOKEN:-test}
githubWebServiceUrl: https://api.github.com
githubOrgForErrorReports: triplea-game
githubRepoForErrorReports: ${ERROR_REPORT_GITHUB_REPO:-test}
githubMapsOrgName: triplea-maps

mapIndexingEnabled: ${MAP_INDEXING_ENABLED:-true}

# if we are using any stubbing, we'll assert that this value is false.
# this is to help guarantee that we do not accidentally use test configuration in prod.
prod: ${PROD_FLAG:-false}
logSqlStatements: false

database:
  driverClass: org.postgresql.Driver
  user: ${DATABASE_USER:-lobby_user}
  password: ${DATABASE_PASSWORD:-lobby}
  url: jdbc:postgresql://${DB_URL:-localhost:5432/lobby_db}
  properties:
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: select 1

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute


logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  loggers:
    # Set this to DEBUG to troubleshoot HTTP 400 "Unable to process JSON" errors.
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: INFO
