server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
database:
  driverClass: org.postgresql.Driver
  user: maps_user
  password: ${DATABASE_PASSWORD:-postgres}
  url: jdbc:postgresql://localhost:5432/maps_db
  properties:
    charSet: UTF-8
  validationQuery: select 1

githubMapsOrgName: ${GITHUB_MAPS_ORG_NAME:-triplea-maps}
githubApiKey: ${GITHUB_API_KEY:-}
githubApiUri: ${GITHUB_API_URI:-https://api.github.com}
