- name: create service user group
  group:
    name: "{{ lobby_server_user }}"

- name: create service user
  user:
    name: "{{ lobby_server_user }}"
    group: "{{ lobby_server_user }}"
    create_home: yes
    system: yes

- name: ensure deployment folder exists
  file:
    state: directory
    path: "{{ lobby_server_home_folder }}"
    mode: "0755"
    owner: "{{ lobby_server_user }}"
    group: "{{ lobby_server_user }}"

- name: upload zip artifact file (prerelease build)
  tags: [prerelease, deploy]
  register: deploy_artifact
  copy:
    src: "{{ lobby_artifact }}"
    dest: "{{ lobby_server_home_folder }}/{{ lobby_artifact }}"
    owner: "{{ lobby_server_user }}"
    group: "{{ lobby_server_user }}"

- name: download zip artifact file (release build)
  tags: [release, deploy]
  register: deploy_artifact
  get_url:
    url: "{{ lobby_artifact_download }}"
    dest: "{{ lobby_server_home_folder }}/{{ lobby_artifact }}"
    owner: "{{ lobby_server_user }}"
    group: "{{ lobby_server_user }}"

- name: extract zip file
  tags: [deploy]
  unarchive:
    remote_src: yes
    src: "{{ lobby_server_home_folder }}/{{ lobby_artifact }}"
    dest: "{{ lobby_server_home_folder }}/"
    owner: "{{ lobby_server_user }}"
    group: "{{ lobby_server_user }}"

- name: install systemd service script
  tags: [deploy]
  register: service_script
  template:
    src: lobby_server.service.j2
    dest: /lib/systemd/system/lobby_server.service
    mode: "644"

- name: reload systemd
  tags: [deploy]
  when: service_script.changed
  systemd:
    daemon_reload: yes

- name: restart service if new artifact was deployed
  tags: [deploy]
  when: (lobby_restart_on_new_deployment) and ((deploy_artifact.changed) or (service_script.changed))
  service:
    name: lobby_server
    state: restarted
    enabled: yes
