name: Static Checks
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Code Convention Checks
        run: .build/code-convention-checks/run
      - name: Find Unused DbUnit Datasets
        run: .build/find-unused-or-unmatched-tests/find-unused-dbunit-datasets
      - name: Check Links are Valid
        run: .build/check-links-and-yaml-syntax/check-links

