name: Deploy Prerelease Server Provisioning
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Prerelease Server Provisioning
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Ansible to Provision Prerelease Servers
        run: |
          pip install ansible==2.9.13
          .build/set-build-number ${{ github.run_number }}
          eval "$(ssh-agent -s)"
          cd infrastructure
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_password
          ./run_ansible --deploy-type full --environment prerelease
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

