name: Deploy Production Server Provisioning
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Production Server Provisioning
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Ansible to Provision Production Servers
        run: |
          cd infrastructure
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_password
          ./run_ansible --deploy-type full --environment production
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

