name: Master Branch Release
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Master Branch Release Actions
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load SSH private key into ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      - name: Build Installers
        run: .build/build-installer
        env:
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
      - name: set build version variables
        run: |
          BUILD_VERSION=$(.build/get-build-version)
          echo "build_version=$BUILD_VERSION" | tee -a $GITHUB_ENV
          echo "release_name=$(date +%Y-%B-%d) - $BUILD_VERSION" | tee -a $GITHUB_ENV
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:        
          artifacts: build/artifacts/*
          tag: ${{ env.build_version }}
          name: ${{ env.release_name }}
          prerelease: true
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Ansible to Deploy
        run: |
          pip install ansible==2.9.13
          cd infrastructure
          echo "$ANSIBLE_VAULT_PASSWORD" > vault_password
          # TODO: temporily running prod deployment in dry run mode until we can avoid
          # players being disconnected (need to avoid restarts)
          ./run_ansible --dry-run --environment production
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
