# Jar files uploaded are used as a maven dependency by server (eg: lobby)
name: Create Http JAR files and upload to github packages
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/upload-http-client-jars.yml'
      - 'game-app/domain-data/**'
      - 'http-clients/**'
      - 'lib/java-extras/**'
      - 'lib/websocket-client/**'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch depth of 0 is needed so we checkout the full revision history
          # The current revision count will be used as our build-number
          fetch-depth: '0'
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: set build version variables
        run: |
          BUILD_VERSION=$(game-app/run/.build/get-build-version)
          echo "JAR_VERSION=$BUILD_VERSION" | tee -a $GITHUB_ENV
      - name: Publish lobby client JAR
        run: ./gradlew :http-clients:lobby-client:publish :game-app:domain-data:publish :lib:java-extras:publish :lib:websocket-client:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
