name: Verify URLs in triplea_maps.yaml

on:
  push:
    paths:
      - 'triplea_maps.yaml'
  pull_request:
    paths:
      - 'triplea_maps.yaml'
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Check URLs in triplea_maps.yaml
        run: .github/workflows/verify-urls-in-triplea-maps.sh
